import ImgCar1 from "../../assets/images/car_1.png"
import ImgCar2 from "../../assets/images/car_2.png"
import ImgCar3 from "../../assets/images/car_3.png"

// Base Image
import CityCar from "../../assets/images/city-car.png";
import ClassicCar from "../../assets/images/classic.png";
import ConvertibleCar from "../../assets/images/convertible.png";
import HatchbackCar from "../../assets/images/hatchback.png";
import JeepCar from "../../assets/images/jeep.png";
import PickupCar from "../../assets/images/pickup.png";
import PoliceCar from "../../assets/images/police.png";
import RetroCar from "../../assets/images/retro.png";
import SedanCar from "../../assets/images/sedan.png";
import SportCar from "../../assets/images/sport.png";
import SportBackCar from "../../assets/images/sport-back.png";
import SuvCar from "../../assets/images/suv.png";
import TaxiCar from "../../assets/images/taxi.png";

// Trait Image
import city_car_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/city-car-cowl-induction.png";
import city_car_engine from "../../assets/images/01-air-intake/engine/city-car-engine.png";
import city_car_intercooler from "../../assets/images/01-air-intake/intercooler/city-car-intercooler.png";
import city_car_ram_intake from "../../assets/images/01-air-intake/ram/city-car-ram-intake.png";
import city_car_shaker from "../../assets/images/01-air-intake/shaker/city-car-shaker.png";
import city_car_avax_rims from "../../assets/images/02-rims/avalanche-rims/city-car-avax-rims.png";
import city_car_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/city-car-bitcoin-rims.png";
import city_car_dollar_rims from "../../assets/images/02-rims/dollar-rims/city-car-dollar-rims.png";
import city_car_eth_rims from "../../assets/images/02-rims/ethereum-rims/city-car-eth-rims.png";
import city_car_rocket_rims from "../../assets/images/02-rims/rocket-rim/city-car-rocket-rims.png";
import city_car_underground_rims from "../../assets/images/02-rims/underground-rim/city-car-underground-rims.png";
import city_car_lips_spoiler from "../../assets/images/03-spoilers/00-lips-spoiler/city-car-lips-spoiler.png";
import city_car_neon_lights from "../../assets/images/04-neon-lights/city-car-neon-lights.png";
import city_car_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/city-car-ethereum-brand.png";
import city_car_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/city-car-bitcoin-brand.png";
import city_car_avax_brand from "../../assets/images/05-brand/02-avax-brand/city-car-avax-brand.png";
import city_car_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/city-car-dollar-brand.png";
import city_car_underground_brand from "../../assets/images/05-brand/04-underground-brand/city-car-underground-brand.png";

import sedan_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/sedan-cowl-induction.png";
import sedan_engine from "../../assets/images/01-air-intake/engine/sedan-engine.png";
import sedan_intercooler from "../../assets/images/01-air-intake/intercooler/sedan-intercooler.png";
import sedan_ram_intake from "../../assets/images/01-air-intake/ram/sedan-ram-intake.png";
import sedan_shaker from "../../assets/images/01-air-intake/shaker/sedan-shaker.png";
import sedan_avax_rims from "../../assets/images/02-rims/avalanche-rims/sedan-avax-rims.png";
import sedan_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/sedan-bitcoin-rims.png";
import sedan_dollar_rims from "../../assets/images/02-rims/dollar-rims/sedan-dollar-rims.png";
import sedan_eth_rims from "../../assets/images/02-rims/ethereum-rims/sedan-eth-rims.png";
import sedan_rocket_rims from "../../assets/images/02-rims/rocket-rim/sedan-rocket-rims.png";
import sedan_underground_rims from "../../assets/images/02-rims/underground-rim/sedan-underground-rims.png";
import sedan_lips_spoiler from "../../assets/images/03-spoilers/00-lips-spoiler/sedan-lips-spoiler.png";
import sedan_round_spoiler from "../../assets/images/03-spoilers/01-round-spoiler/sedan-round-spoiler.png";
import sedan_pedestal_spoiler from "../../assets/images/03-spoilers/03-pedestal-spoiler/sedan-pedestal-spoiler.png";
import sedan_neon_lights from "../../assets/images/04-neon-lights/sedan-neon-lights.png";
import sedan_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/sedan-ethereum-brand.png";
import sedan_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/sedan-bitcoin-brand.png";
import sedan_avax_brand from "../../assets/images/05-brand/02-avax-brand/sedan-avax-brand.png";
import sedan_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/sedan-dollar-brand.png";
import sedan_underground_brand from "../../assets/images/05-brand/04-underground-brand/sedan-underground-brand.png";

import hatchback_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/hatchback-cowl-induction.png";
import hatchback_engine from "../../assets/images/01-air-intake/engine/hatchback-engine.png";
import hatchback_intercooler from "../../assets/images/01-air-intake/intercooler/hatchback-intercooler.png";
import hatchback_ram_intake from "../../assets/images/01-air-intake/ram/hatchback-ram-intake.png";
import hatchback_shaker from "../../assets/images/01-air-intake/shaker/hatchback-shaker.png";
import hatchback_avax_rims from "../../assets/images/02-rims/avalanche-rims/hatchback-avax-rims.png";
import hatchback_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/hatchback-bitcoin-rims.png";
import hatchback_dollar_rims from "../../assets/images/02-rims/dollar-rims/hatchback-dollar-rims.png";
import hatchback_eth_rims from "../../assets/images/02-rims/ethereum-rims/hatchback-eth-rims.png";
import hatchback_rocket_rims from "../../assets/images/02-rims/rocket-rim/hatchback-rocket-rims.png";
import hatchback_underground_rims from "../../assets/images/02-rims/underground-rim/hatchback-underground-rims.png";
import hatchback_lips_spoiler from "../../assets/images/03-spoilers/00-lips-spoiler/hatchback-lips-spoiler.png";
import hatchback_round_spoiler from "../../assets/images/03-spoilers/01-round-spoiler/hatchback-round-spoiler.png";
import hatchback_roof_spoiler from "../../assets/images/03-spoilers/02-roof-spoiler/hatchback-roof-spoiler.png";
import hatchback_pedestal_spoiler from "../../assets/images/03-spoilers/03-pedestal-spoiler/hatchback-pedestal-spoiler.png";
import hatchback_neon_lights from "../../assets/images/04-neon-lights/hatchback-neon-lights.png";
import hatchback_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/hatchback-ethereum-brand.png";
import hatchback_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/hatchback-bitcoin-brand.png";
import hatchback_avax_brand from "../../assets/images/05-brand/02-avax-brand/hatchback-avax-brand.png";
import hatchback_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/hatchback-dollar-brand.png";
import hatchback_underground_brand from "../../assets/images/05-brand/04-underground-brand/hatchback-underground-brand.png";

import jeep_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/jeep-cowl-induction.png";
import jeep_engine from "../../assets/images/01-air-intake/engine/jeep-engine.png";
import jeep_intercooler from "../../assets/images/01-air-intake/intercooler/jeep-intercooler.png";
import jeep_ram_intake from "../../assets/images/01-air-intake/ram/jeep-ram-intake.png";
import jeep_shaker from "../../assets/images/01-air-intake/shaker/jeep-shaker.png";
import jeep_avax_rims from "../../assets/images/02-rims/avalanche-rims/jeep-avax-rims.png";
import jeep_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/jeep-bitcoin-rims.png";
import jeep_dollar_rims from "../../assets/images/02-rims/dollar-rims/jeep-dollar-rims.png";
import jeep_eth_rims from "../../assets/images/02-rims/ethereum-rims/jeep-eth-rims.png";
import jeep_rocket_rims from "../../assets/images/02-rims/rocket-rim/jeep-rocket-rims.png";
import jeep_underground_rims from "../../assets/images/02-rims/underground-rim/jeep-underground-rims.png";
import jeep_neon_lights from "../../assets/images/04-neon-lights/jeep-neon-lights.png";
import jeep_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/jeep-ethereum-brand.png";
import jeep_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/jeep-bitcoin-brand.png";
import jeep_avax_brand from "../../assets/images/05-brand/02-avax-brand/jeep-avax-brand.png";
import jeep_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/jeep-dollar-brand.png";
import jeep_underground_brand from "../../assets/images/05-brand/04-underground-brand/jeep-underground-brand.png";

import pickup_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/pickup-cowl-induction.png";
import pickup_engine from "../../assets/images/01-air-intake/engine/pickup-engine.png";
import pickup_intercooler from "../../assets/images/01-air-intake/intercooler/pickup-intercooler.png";
import pickup_ram_intake from "../../assets/images/01-air-intake/ram/pickup-ram-intake.png";
import pickup_shaker from "../../assets/images/01-air-intake/shaker/pickup-shaker.png";
import pickup_avax_rims from "../../assets/images/02-rims/avalanche-rims/pickup-avax-rims.png";
import pickup_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/pickup-bitcoin-rims.png";
import pickup_dollar_rims from "../../assets/images/02-rims/dollar-rims/pickup-dollar-rims.png";
import pickup_eth_rims from "../../assets/images/02-rims/ethereum-rims/pickup-eth-rims.png";
import pickup_rocket_rims from "../../assets/images/02-rims/rocket-rim/pickup-rocket-rims.png";
import pickup_underground_rims from "../../assets/images/02-rims/underground-rim/pickup-underground-rims.png";
import pickup_lips_spoiler from "../../assets/images/03-spoilers/00-lips-spoiler/pickup-lips-spoiler.png";
import pickup_round_spoiler from "../../assets/images/03-spoilers/01-round-spoiler/pickup-round-spoiler.png";
import pickup_roof_spoiler from "../../assets/images/03-spoilers/02-roof-spoiler/pickup-roof-spoiler.png";
import pickup_neon_lights from "../../assets/images/04-neon-lights/pickup-neon-lights.png";
import pickup_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/pickup-ethereum-brand.png";
import pickup_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/pickup-bitcoin-brand.png";
import pickup_avax_brand from "../../assets/images/05-brand/02-avax-brand/pickup-avax-brand.png";
import pickup_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/pickup-dollar-brand.png";
import pickup_underground_brand from "../../assets/images/05-brand/04-underground-brand/pickup-underground-brand.png";

import suv_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/suv-cowl-induction.png";
import suv_engine from "../../assets/images/01-air-intake/engine/suv-engine.png";
import suv_intercooler from "../../assets/images/01-air-intake/intercooler/suv-intercooler.png";
import suv_ram_intake from "../../assets/images/01-air-intake/ram/suv-ram-intake.png";
import suv_shaker from "../../assets/images/01-air-intake/shaker/suv-shaker.png";
import suv_avax_rims from "../../assets/images/02-rims/avalanche-rims/suv-avax-rims.png";
import suv_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/suv-bitcoin-rims.png";
import suv_dollar_rims from "../../assets/images/02-rims/dollar-rims/suv-dollar-rims.png";
import suv_eth_rims from "../../assets/images/02-rims/ethereum-rims/suv-eth-rims.png";
import suv_rocket_rims from "../../assets/images/02-rims/rocket-rim/suv-rocket-rims.png";
import suv_underground_rims from "../../assets/images/02-rims/underground-rim/suv-underground-rims.png";
import suv_lips_spoiler from "../../assets/images/03-spoilers/00-lips-spoiler/suv-lips-spoiler.png";
import suv_round_spoiler from "../../assets/images/03-spoilers/01-round-spoiler/suv-round-spoiler.png";
import suv_roof_spoiler from "../../assets/images/03-spoilers/02-roof-spoiler/suv-roof-spoiler.png";
import suv_pedestal_spoiler from "../../assets/images/03-spoilers/03-pedestal-spoiler/suv-pedestal-spoiler.png";
import suv_neon_lights from "../../assets/images/04-neon-lights/suv-neon-lights.png";
import suv_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/suv-ethereum-brand.png";
import suv_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/suv-bitcoin-brand.png";
import suv_avax_brand from "../../assets/images/05-brand/02-avax-brand/suv-avax-brand.png";
import suv_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/suv-dollar-brand.png";
import suv_underground_brand from "../../assets/images/05-brand/04-underground-brand/suv-underground-brand.png";

import police_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/police-cowl-induction.png";
import police_engine from "../../assets/images/01-air-intake/engine/police-engine.png";
import police_intercooler from "../../assets/images/01-air-intake/intercooler/police-intercooler.png";
import police_ram_intake from "../../assets/images/01-air-intake/ram/police-ram-intake.png";
import police_shaker from "../../assets/images/01-air-intake/shaker/police-shaker.png";
import police_avax_rims from "../../assets/images/02-rims/avalanche-rims/police-avax-rims.png";
import police_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/police-bitcoin-rims.png";
import police_dollar_rims from "../../assets/images/02-rims/dollar-rims/police-dollar-rims.png";
import police_eth_rims from "../../assets/images/02-rims/ethereum-rims/police-eth-rims.png";
import police_rocket_rims from "../../assets/images/02-rims/rocket-rim/police-rocket-rims.png";
import police_underground_rims from "../../assets/images/02-rims/underground-rim/police-underground-rims.png";
import police_lips_spoiler from "../../assets/images/03-spoilers/00-lips-spoiler/police-lips-spoiler.png";
import police_round_spoiler from "../../assets/images/03-spoilers/01-round-spoiler/police-round-spoiler.png";
import police_roof_spoiler from "../../assets/images/03-spoilers/02-roof-spoiler/police-roof-spoiler.png";
import police_pedestal_spoiler from "../../assets/images/03-spoilers/03-pedestal-spoiler/police-pedestal-spoiler.png";
import police_neon_lights from "../../assets/images/04-neon-lights/police-neon-lights.png";
import police_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/police-ethereum-brand.png";
import police_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/police-bitcoin-brand.png";
import police_avax_brand from "../../assets/images/05-brand/02-avax-brand/police-avax-brand.png";
import police_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/police-dollar-brand.png";
import police_underground_brand from "../../assets/images/05-brand/04-underground-brand/police-underground-brand.png";

import convertible_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/convertible-cowl-induction.png";
import convertible_engine from "../../assets/images/01-air-intake/engine/convertible-engine.png";
import convertible_intercooler from "../../assets/images/01-air-intake/intercooler/convertible-intercooler.png";
import convertible_ram_intake from "../../assets/images/01-air-intake/ram/convertible-ram-intake.png";
import convertible_shaker from "../../assets/images/01-air-intake/shaker/convertible-shaker.png";
import convertible_avax_rims from "../../assets/images/02-rims/avalanche-rims/convertible-avax-rims.png";
import convertible_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/convertible-bitcoin-rims.png";
import convertible_dollar_rims from "../../assets/images/02-rims/dollar-rims/convertible-dollar-rims.png";
import convertible_eth_rims from "../../assets/images/02-rims/ethereum-rims/convertible-eth-rims.png";
import convertible_rocket_rims from "../../assets/images/02-rims/rocket-rim/convertible-rocket-rims.png";
import convertible_underground_rims from "../../assets/images/02-rims/underground-rim/convertible-underground-rims.png";
import convertible_lips_spoiler from "../../assets/images/03-spoilers/00-lips-spoiler/convertible-lips-spoiler.png";
import convertible_round_spoiler from "../../assets/images/03-spoilers/01-round-spoiler/convertible-round-spoiler.png";
import convertible_pedestal_spoiler from "../../assets/images/03-spoilers/03-pedestal-spoiler/convertible-pedestal-spoiler.png";
import convertible_neon_lights from "../../assets/images/04-neon-lights/convertible-neon-lights.png";
import convertible_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/convertible-ethereum-brand.png";
import convertible_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/convertible-bitcoin-brand.png";
import convertible_avax_brand from "../../assets/images/05-brand/02-avax-brand/convertible-avax-brand.png";
import convertible_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/convertible-dollar-brand.png";
import convertible_underground_brand from "../../assets/images/05-brand/04-underground-brand/convertible-underground-brand.png";

import taxi_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/taxi-cowl-induction.png";
import taxi_engine from "../../assets/images/01-air-intake/engine/taxi-engine.png";
import taxi_intercooler from "../../assets/images/01-air-intake/intercooler/taxi-intercooler.png";
import taxi_ram_intake from "../../assets/images/01-air-intake/ram/taxi-ram-intake.png";
import taxi_shaker from "../../assets/images/01-air-intake/shaker/taxi-shaker.png";
import taxi_avax_rims from "../../assets/images/02-rims/avalanche-rims/taxi-avax-rims.png";
import taxi_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/taxi-bitcoin-rims.png";
import taxi_dollar_rims from "../../assets/images/02-rims/dollar-rims/taxi-dollar-rims.png";
import taxi_eth_rims from "../../assets/images/02-rims/ethereum-rims/taxi-eth-rims.png";
import taxi_rocket_rims from "../../assets/images/02-rims/rocket-rim/taxi-rocket-rims.png";
import taxi_underground_rims from "../../assets/images/02-rims/underground-rim/taxi-underground-rims.png";
import taxi_lips_spoiler from "../../assets/images/03-spoilers/00-lips-spoiler/taxi-lips-spoiler.png";
import taxi_round_spoiler from "../../assets/images/03-spoilers/01-round-spoiler/taxi-round-spoiler.png";
import taxi_roof_spoiler from "../../assets/images/03-spoilers/02-roof-spoiler/taxi-roof-spoiler.png";
import taxi_pedestal_spoiler from "../../assets/images/03-spoilers/03-pedestal-spoiler/taxi-pedestal-spoiler.png";
import taxi_neon_lights from "../../assets/images/04-neon-lights/taxi-neon-lights.png";
import taxi_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/taxi-ethereum-brand.png";
import taxi_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/taxi-bitcoin-brand.png";
import taxi_avax_brand from "../../assets/images/05-brand/02-avax-brand/taxi-avax-brand.png";
import taxi_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/taxi-dollar-brand.png";
import taxi_underground_brand from "../../assets/images/05-brand/04-underground-brand/taxi-underground-brand.png";

import sport_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/sport-cowl-induction.png";
import sport_engine from "../../assets/images/01-air-intake/engine/sport-engine.png";
import sport_intercooler from "../../assets/images/01-air-intake/intercooler/sport-intercooler.png";
import sport_ram_intake from "../../assets/images/01-air-intake/ram/sport-ram-intake.png";
import sport_shaker from "../../assets/images/01-air-intake/shaker/sport-shaker.png";
import sport_avax_rims from "../../assets/images/02-rims/avalanche-rims/sport-avax-rims.png";
import sport_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/sport-bitcoin-rims.png";
import sport_dollar_rims from "../../assets/images/02-rims/dollar-rims/sport-dollar-rims.png";
import sport_eth_rims from "../../assets/images/02-rims/ethereum-rims/sport-eth-rims.png";
import sport_rocket_rims from "../../assets/images/02-rims/rocket-rim/sport-rocket-rims.png";
import sport_underground_rims from "../../assets/images/02-rims/underground-rim/sport-underground-rims.png";
import sport_round_spoiler from "../../assets/images/03-spoilers/01-round-spoiler/sport-round-spoiler.png";
import sport_pedestal_spoiler from "../../assets/images/03-spoilers/03-pedestal-spoiler/sport-pedestal-spoiler.png";
import sport_neon_lights from "../../assets/images/04-neon-lights/sport-neon-lights.png";
import sport_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/sport-ethereum-brand.png";
import sport_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/sport-bitcoin-brand.png";
import sport_avax_brand from "../../assets/images/05-brand/02-avax-brand/sport-avax-brand.png";
import sport_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/sport-dollar-brand.png";
import sport_underground_brand from "../../assets/images/05-brand/04-underground-brand/sport-underground-brand.png";

import classic_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/classic-cowl-induction.png";
import classic_engine from "../../assets/images/01-air-intake/engine/classic-engine.png";
import classic_intercooler from "../../assets/images/01-air-intake/intercooler/classic-intercooler.png";
import classic_ram_intake from "../../assets/images/01-air-intake/ram/classic-ram-intake.png";
import classic_shaker from "../../assets/images/01-air-intake/shaker/classic-shaker.png";
import classic_avax_rims from "../../assets/images/02-rims/avalanche-rims/classic-avax-rims.png";
import classic_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/classic-bitcoin-rims.png";
import classic_dollar_rims from "../../assets/images/02-rims/dollar-rims/classic-dollar-rims.png";
import classic_eth_rims from "../../assets/images/02-rims/ethereum-rims/classic-eth-rims.png";
import classic_rocket_rims from "../../assets/images/02-rims/rocket-rim/classic-rocket-rims.png";
import classic_underground_rims from "../../assets/images/02-rims/underground-rim/classic-underground-rims.png";
import classic_lips_spoiler from "../../assets/images/03-spoilers/00-lips-spoiler/classic-lips-spoiler.png";
import classic_round_spoiler from "../../assets/images/03-spoilers/01-round-spoiler/classic-round-spoiler.png";
import classic_pedestal_spoiler from "../../assets/images/03-spoilers/03-pedestal-spoiler/classic-pedestal-spoiler.png";
import classic_neon_lights from "../../assets/images/04-neon-lights/classic-neon-lights.png";
import classic_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/classic-ethereum-brand.png";
import classic_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/classic-bitcoin-brand.png";
import classic_avax_brand from "../../assets/images/05-brand/02-avax-brand/classic-avax-brand.png";
import classic_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/classic-dollar-brand.png";
import classic_underground_brand from "../../assets/images/05-brand/04-underground-brand/classic-underground-brand.png";

import retro_cowl_induction from "../../assets/images/01-air-intake/cowl-induction/retro-cowl-induction.png";
import retro_engine from "../../assets/images/01-air-intake/engine/retro-engine.png";
import retro_intercooler from "../../assets/images/01-air-intake/intercooler/retro-intercooler.png";
import retro_ram_intake from "../../assets/images/01-air-intake/ram/retro-ram-intake.png";
import retro_shaker from "../../assets/images/01-air-intake/shaker/retro-shaker.png";
import retro_avax_rims from "../../assets/images/02-rims/avalanche-rims/retro-avax-rims.png";
import retro_bitcoin_rims from "../../assets/images/02-rims/bitcoin-rims/retro-bitcoin-rims.png";
import retro_dollar_rims from "../../assets/images/02-rims/dollar-rims/retro-dollar-rims.png";
import retro_eth_rims from "../../assets/images/02-rims/ethereum-rims/retro-eth-rims.png";
import retro_rocket_rims from "../../assets/images/02-rims/rocket-rim/retro-rocket-rims.png";
import retro_underground_rims from "../../assets/images/02-rims/underground-rim/retro-underground-rims.png";
import retro_lips_spoiler from "../../assets/images/03-spoilers/00-lips-spoiler/retro-lips-spoiler.png";
import retro_round_spoiler from "../../assets/images/03-spoilers/01-round-spoiler/retro-round-spoiler.png";
import retro_pedestal_spoiler from "../../assets/images/03-spoilers/03-pedestal-spoiler/retro-pedestal-spoiler.png";
import retro_neon_lights from "../../assets/images/04-neon-lights/retro-neon-lights.png";
import retro_ethereum_brand from "../../assets/images/05-brand/00-ethereum-brand/retro-ethereum-brand.png";
import retro_bitcoin_brand from "../../assets/images/05-brand/01-bitcoin-brand/retro-bitcoin-brand.png";
import retro_avax_brand from "../../assets/images/05-brand/02-avax-brand/retro-avax-brand.png";
import retro_dollar_brand from "../../assets/images/05-brand/03-dollar-brand/retro-dollar-brand.png";
import retro_underground_brand from "../../assets/images/05-brand/04-underground-brand/retro-underground-brand.png";

export const traitsList = [
  {
    id:0,
    img:city_car_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:0,
    img:city_car_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:0,
    img:city_car_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:0,
    img:city_car_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:0,
    img:city_car_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:0,
    img:city_car_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE RIMS",
    rarity: "EPIC",
  },
  {
    id:0,
    img:city_car_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN RIMS",
    rarity: "RARE",
  },
  {
    id:0,
    img:city_car_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:0,
    img:city_car_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:0,
    img:city_car_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:0,
    img:city_car_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:0,
    img:city_car_lips_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "LIPS",
    rarity: "UNCOMMON",
  },
  {
    id:0,
    img:city_car_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:0,
    img:city_car_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:0,
    img:city_car_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:0,
    img:city_car_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:0,
    img:city_car_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:0,
    img:city_car_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:1,
    img:sedan_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:1,
    img:sedan_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:1,
    img:sedan_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:1,
    img:sedan_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:1,
    img:sedan_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:1,
    img:sedan_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:1,
    img:sedan_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:1,
    img:sedan_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+2",
    name: "DOLLAR",
    rarity: "RARE",
  },
  {
    id:1,
    img:sedan_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:1,
    img:sedan_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:1,
    img:sedan_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:1,
    img:sedan_lips_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "LIPS",
    rarity: "UNCOMMON",
  },
  {
    id:1,
    img:sedan_round_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+1",
    name: "ROUND",
    rarity: "RARE",
  },
  {
    id:1,
    img:sedan_pedestal_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "PEDESTAL",
    rarity: "EPIC",
  },
  {
    id:1,
    img:sedan_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:1,
    img:sedan_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:1,
    img:sedan_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:1,
    img:sedan_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:1,
    img:sedan_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:1,
    img:sedan_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:2,
    img:hatchback_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:2,
    img:hatchback_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:2,
    img:hatchback_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:2,
    img:hatchback_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:2,
    img:hatchback_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:2,
    img:hatchback_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:2,
    img:hatchback_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:2,
    img:hatchback_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:2,
    img:hatchback_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:2,
    img:hatchback_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:2,
    img:hatchback_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:2,
    img:hatchback_lips_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "LIPS",
    rarity: "UNCOMMON",
  },
  {
    id:2,
    img:hatchback_round_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+1",
    name: "ROUND",
    rarity: "RARE",
  },
  {
    id:2,
    img:hatchback_roof_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "ROOF",
    rarity: "UNCOMMON",
  },
  {
    id:2,
    img:hatchback_pedestal_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "PEDESTAL",
    rarity: "EPIC",
  },
  {
    id:2,
    img:hatchback_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:2,
    img:hatchback_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:2,
    img:hatchback_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:2,
    img:hatchback_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:2,
    img:hatchback_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:2,
    img:hatchback_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:3,
    img:jeep_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:3,
    img:jeep_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:3,
    img:jeep_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:3,
    img:jeep_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:3,
    img:jeep_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:3,
    img:jeep_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:3,
    img:jeep_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:3,
    img:jeep_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:3,
    img:jeep_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:3,
    img:jeep_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:3,
    img:jeep_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:3,
    img:jeep_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:3,
    img:jeep_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:3,
    img:jeep_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:3,
    img:jeep_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:3,
    img:jeep_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:3,
    img:jeep_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:4,
    img:pickup_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:4,
    img:pickup_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:4,
    img:pickup_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:4,
    img:pickup_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:4,
    img:pickup_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:4,
    img:pickup_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:4,
    img:pickup_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:4,
    img:pickup_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:4,
    img:pickup_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:4,
    img:pickup_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:4,
    img:pickup_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:4,
    img:pickup_lips_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "LIPS",
    rarity: "UNCOMMON",
  },
  {
    id:4,
    img:pickup_round_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+1",
    name: "ROUND",
    rarity: "RARE",
  },
  {
    id:4,
    img:pickup_roof_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "ROOF",
    rarity: "UNCOMMON",
  },
  {
    id:4,
    img:pickup_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:4,
    img:pickup_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:4,
    img:pickup_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:4,
    img:pickup_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:4,
    img:pickup_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:4,
    img:pickup_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:5,
    img:suv_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:5,
    img:suv_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:5,
    img:suv_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:5,
    img:suv_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:5,
    img:suv_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:5,
    img:suv_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:5,
    img:suv_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:5,
    img:suv_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:5,
    img:suv_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:5,
    img:suv_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:5,
    img:suv_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:5,
    img:suv_lips_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "LIPS",
    rarity: "UNCOMMON",
  },
  {
    id:5,
    img:suv_round_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+1",
    name: "ROUND",
    rarity: "RARE",
  },
  {
    id:5,
    img:suv_roof_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "ROOF",
    rarity: "UNCOMMON",
  },
  {
    id:5,
    img:suv_pedestal_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "PEDESTAL",
    rarity: "EPIC",
  },
  {
    id:5,
    img:suv_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:5,
    img:suv_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:5,
    img:suv_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:5,
    img:suv_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:5,
    img:suv_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:5,
    img:suv_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:6,
    img:police_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:6,
    img:police_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:6,
    img:police_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:6,
    img:police_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:6,
    img:police_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:6,
    img:police_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:6,
    img:police_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:6,
    img:police_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:6,
    img:police_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:6,
    img:police_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:6,
    img:police_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:6,
    img:police_lips_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "LIPS",
    rarity: "UNCOMMON",
  },
  {
    id:6,
    img:police_round_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+1",
    name: "ROUND",
    rarity: "RARE",
  },
  {
    id:6,
    img:police_roof_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "ROOF",
    rarity: "UNCOMMON",
  },
  {
    id:6,
    img:police_pedestal_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "PEDESTAL",
    rarity: "EPIC",
  },
  {
    id:6,
    img:police_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:6,
    img:police_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:6,
    img:police_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:6,
    img:police_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:6,
    img:police_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:6,
    img:police_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:7,
    img:convertible_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:7,
    img:convertible_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:7,
    img:convertible_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:7,
    img:convertible_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:7,
    img:convertible_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:7,
    img:convertible_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:7,
    img:convertible_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:7,
    img:convertible_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:7,
    img:convertible_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:7,
    img:convertible_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:7,
    img:convertible_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:7,
    img:convertible_lips_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "LIPS",
    rarity: "UNCOMMON",
  },
  {
    id:7,
    img:convertible_round_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+1",
    name: "ROUND",
    rarity: "RARE",
  },
  {
    id:7,
    img:convertible_pedestal_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "PEDESTAL",
    rarity: "EPIC",
  },
  {
    id:7,
    img:convertible_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:7,
    img:convertible_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:7,
    img:convertible_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:7,
    img:convertible_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:7,
    img:convertible_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:7,
    img:convertible_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:8,
    img:taxi_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:8,
    img:taxi_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:8,
    img:taxi_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:8,
    img:taxi_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:8,
    img:taxi_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:8,
    img:taxi_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:8,
    img:taxi_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:8,
    img:taxi_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:8,
    img:taxi_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:8,
    img:taxi_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:8,
    img:taxi_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:8,
    img:taxi_lips_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "LIPS",
    rarity: "UNCOMMON",
  },
  {
    id:8,
    img:taxi_round_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+1",
    name: "ROUND",
    rarity: "RARE",
  },
  {
    id:8,
    img:taxi_roof_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "ROOF",
    rarity: "UNCOMMON",
  },
  {
    id:8,
    img:taxi_pedestal_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "PEDESTAL",
    rarity: "EPIC",
  },
  {
    id:8,
    img:taxi_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:8,
    img:taxi_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:8,
    img:taxi_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:8,
    img:taxi_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:8,
    img:taxi_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:8,
    img:taxi_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:9,
    img:sport_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:9,
    img:sport_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:9,
    img:sport_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:9,
    img:sport_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:9,
    img:sport_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:9,
    img:sport_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:9,
    img:sport_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:9,
    img:sport_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:9,
    img:sport_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:9,
    img:sport_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:9,
    img:sport_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:9,
    img:sport_round_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+1",
    name: "ROUND",
    rarity: "RARE",
  },
  {
    id:9,
    img:sport_pedestal_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "PEDESTAL",
    rarity: "EPIC",
  },
  {
    id:9,
    img:sport_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:9,
    img:sport_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:9,
    img:sport_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:9,
    img:sport_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:9,
    img:sport_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:9,
    img:sport_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:10,
    img:classic_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:10,
    img:classic_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:10,
    img:classic_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:10,
    img:classic_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:10,
    img:classic_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:10,
    img:classic_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:10,
    img:classic_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:10,
    img:classic_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:10,
    img:classic_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:10,
    img:classic_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:10,
    img:classic_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:10,
    img:classic_lips_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "LIPS",
    rarity: "UNCOMMON",
  },
  {
    id:10,
    img:classic_round_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+1",
    name: "ROUND",
    rarity: "RARE",
  },
  {
    id:10,
    img:classic_pedestal_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "PEDESTAL",
    rarity: "EPIC",
  },
  {
    id:10,
    img:classic_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:10,
    img:classic_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:10,
    img:classic_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:10,
    img:classic_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:10,
    img:classic_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:10,
    img:classic_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },

  {
    id:11,
    img:retro_cowl_induction,
    rarity_level:"",
    available: "",
    car_description: "Air intake can make the difference between a long race and decreasing the wear & tear, maintaning your engine cooler for a long time. It's amust if you wanna get the most out of your",
    acceleration: "+1",
    wearability: "",
    name: "COWL INDUCTION",
    rarity: "UNCOMMON",
  },
  {
    id:11,
    img:retro_engine,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+3",
    wearability: "+1",
    name: "ENGINE",
    rarity: "LEGENDARY",
  },
  {
    id:11,
    img:retro_intercooler,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+2",
    name: "INTERCOOLER",
    rarity: "EPIC",
  },
  {
    id:11,
    img:retro_ram_intake,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "+1",
    name: "RAM",
    rarity: "RARE",
  },
  {
    id:11,
    img:retro_shaker,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+1",
    wearability: "",
    name: "SHAKER",
    rarity: "UNCOMMON",
  },
  {
    id:11,
    img:retro_avax_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:11,
    img:retro_bitcoin_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "BITCOIN",
    rarity: "RARE",
  },
  {
    id:11,
    img:retro_dollar_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "",
    wearability: "+1",
    name: "DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:11,
    img:retro_eth_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "+2",
    name: "ETHEREUM",
    rarity: "EPIC",
  },
  {
    id:11,
    img:retro_rocket_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "ROCKET",
    rarity: "UNCOMMON",
  },
  {
    id:11,
    img:retro_underground_rims,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+4",
    wearability: "",
    name: "UNDERGROUND",
    rarity: "LEGENDARY",
  },
  {
    id:11,
    img:retro_lips_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+1",
    wearability: "",
    name: "LIPS",
    rarity: "UNCOMMON",
  },
  {
    id:11,
    img:retro_round_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+1",
    name: "ROUND",
    rarity: "RARE",
  },
  {
    id:11,
    img:retro_pedestal_spoiler,
    rarity_level:"",
    available: "",
    car_description: "RIMS ARE ONE OF THE FINEST ASPECTS OF A CAR. IT’S SHINING AND SPINING WILL MAKE THE DIFFERENCE BETWEEN A CAR AND A SPACE SHIP",
    acceleration: "+2",
    wearability: "+2",
    name: "PEDESTAL",
    rarity: "EPIC",
  },
  {
    id:11,
    img:retro_neon_lights,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "NEON",
    rarity: "EPIC",
  },
  {
    id:11,
    img:retro_ethereum_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "",
    name: "BRAND ETHEREUM",
    rarity: "RARE",
  },
  {
    id:11,
    img:retro_bitcoin_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+2",
    name: "BRAND BITCOIN",
    rarity: "RARE",
  },
  {
    id:11,
    img:retro_avax_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND AVALANCHE",
    rarity: "EPIC",
  },
  {
    id:11,
    img:retro_dollar_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "",
    wearability: "+1",
    name: "BRAND DOLLAR",
    rarity: "UNCOMMON",
  },
  {
    id:11,
    img:retro_underground_brand,
    rarity_level:"",
    available: "",
    car_description: "",
    acceleration: "+2",
    wearability: "+2",
    name: "BRAND UNDERGROUND",
    rarity: "LEGENDARY",
  },
]

export const carsList = [
  {
    id:0,
    img:CityCar,
    name:"CITY CAR",
    rarity:"COMMON",
    rarity_level:"1",
    available: "1,500",
    car_description: "The city car is well known for it’s mobility around the city. However,if used properly it can give you great results in underground races",
    acceleration: "10",
    wearability: "60"
  },
  {
    id:1,
    img:SedanCar,
    name:"SEDAN",
    rarity:"COMMON",
    rarity_level:"1",
    available: "1,500",
    car_description: "The sedan is great for using in short and long distances on paved roads. It can reach great velocities and maintain a decent balance on races",
    acceleration: "12",
    wearability: "70"
  },
  {
    id:2,
    img:HatchbackCar,
    name:"HATCHBACK",
    rarity:"COMMON",
    rarity_level:"1",
    available: "1,500",
    car_description: "Hatchbacks have lots of utility as they are a nice combination between sedan and suvs. With a nice styling and great comfort represent a Good option for a quick race",
    acceleration: "14",
    wearability: "65"
  },
  {
    id:3,
    img:JeepCar,
    name:"JEEP",
    rarity:"UNCOMMON",
    rarity_level:"2",
    available: "800",
    car_description: "The jeep is a versatile machine that can be used accross multiple roads and scenarios. However it’s lack of maniobrability can cause some pain to it’s driver on a city race",
    acceleration: "12",
    wearability: "80"
  },
  {
    id:4,
    img:PickupCar,
    name:"PICKUP",
    rarity: "UNCOMMON",
    rarity_level:"2",
    available: "1,100",
    car_description: "The pickup truck is the perfect combination between power and mobility. Can be well used over cities and roads",
    acceleration: "13",
    wearability: "75"
  },
  {
    id:5,
    img:SuvCar,
    name:"SUV",
    rarity: "UNCOMMON",
    rarity_level:"2",
    available: "1,100",
    car_description: "Suvs are an elegant and sophisticated yet useful option for a car, with huge spacing, drivers get an assured comfort. Despite is size, it’s still a pretty decent option to consider for racing",
    acceleration: "14",
    wearability: "75"
  },
  {
    id:6,
    img:PoliceCar,
    name:"POLICE CAR",
    rarity: "RARE",
    rarity_level:"3",
    available: "500",
    car_description: "Police cars are very well equiped to face a race on the city and the ground. However, be careful if you choose to race on this machine, you could lose it all",
    acceleration: "17",
    wearability: "80"
  },
  {
    id:7,
    img:ConvertibleCar,
    name:"CONVERTIBLE",
    rarity:"RARE",
    rarity_level:"3",
    available: "600",
    car_description: "The convertible model is a luxury car best suited for beach and wind lovers. Don’t hesitate on taking some pretty girls on the road and get all the looks in every race you take",
    acceleration: "16",
    wearability: "70"
  },
  {
    id:8,
    img:TaxiCar,
    name:"TAXI CAR",
    rarity:"RARE",
    rarity_level:"3",
    available: "500",
    car_description: "Taxis are a huge utility model in underground. run races, take publicity and complete Passenger trips to get extra rewards on every race",
    acceleration: "15",
    wearability: "75"
  },
  {
    id:9,
    img:SportCar,
    name:"SPORT",
    rarity:"EPIC",
    rarity_level:"4",
    available: "300",
    car_description: "The sport car is one of the fastest cars available. Combine best of the line fashion style, maniobrability and high speed to get the most out of every race",
    acceleration: "22",
    wearability: "85"
  },
  {
    id:10,
    img:ClassicCar,
    name:"CLASSIC",
    rarity:"EPIC",
    rarity_level:"4",
    available: "300",
    car_description: "The old classic from 80’s to 90’s can’t be left out in this collection. It’s a combination between power and old fashioned style that will make you feel like the old days",
    acceleration: "20",
    wearability: "90"
  },
  {
    id:11,
    img:RetroCar,
    name:"RETRO",
    rarity: "EPIC",
    rarity_level:"4",
    available: "300",
    car_description: "We all love retro, so why not include a version of the father of many cars. Huge wearability and a decent power speed make this car is a must have in your collection",
    acceleration: "18",
    wearability: "100"
  },
]